### ISSUE TITLE
[Feature] - Add new Twitter/X logo

### ISSUE THREAD

**Issue by DaniruKun** [RobBrazier/svelte-awesome#1212]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RobBrazier** [comment]
Hi, unfortunately I won't be doing this
only fontawesome v4 icons are bundled, these are no longer updated, if you want the X icon, please import fontawesome v6 brands and use the one from there https://fontawesome.com/icons/x-twitter?f=brands&s=solid
