### ISSUE TITLE
Sapper Error - TypeError: _components_Icon_html__WEBPACK_IMPORTED_MODULE_0__.default.register is not a function

### ISSUE THREAD

**Issue by btakita** [RobBrazier/svelte-awesome#221]
When importing an icon:

```javascript
import 'svelte-awesome/icons/chevron-left.js'
```

The following error occurs:

```
TypeError: _components_Icon_html__WEBPACK_IMPORTED_MODULE_0__.default.register is not a function
```

**Comment by RobBrazier** [comment]
I haven't actually tested this with sapper, I'll have a look - thanks

**Comment by btakita** [comment]
It seems like `setup` (`Icon.html`) is not invoked during SSR.

**Comment by btakita** [comment]
It looks like `setup` (https://github.com/RobBrazier/svelte-awesome/blob/master/src/components/Icon.html#L57) is not called when performing SSR.

**Comment by btakita** [comment]
@RobBrazier Sorry about the commit spam. I tried a few approaches to get it working in SSR, but could not seem to figure out how to keep `Icon.register()` & `Icon.icons`. I'm not sure how you would want this handled, so I'll pass this to you.

**Comment by btakita** [comment]
https://github.com/sveltejs/svelte/issues/817

**Comment by burkostya** [comment]
@RobBrazier Any thoughts? Looks like @btakita fixed it.

**Comment by RobBrazier** [comment]
I haven't had a chance to look at it yet, I'll try and give it a go over the weekend, but I'm getting an error from the svelte plugin when trying to use the getter method
```
get icons() {
  return icons;
}
```

@btakita did you manage to get anywhere in the end? I see you had another go early this month.

Is this issue just on any sapper application, no particular requirements?

**Comment by antony** [comment]
I've created a fresh Sapper application just to determine how far from working this project might be.

Simply including the Icon component on a page causes the following stacktrace:

```bash

500
<Icon> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

Error: <Icon> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at validateSsrComponent (webpack:///./node_modules/svelte/shared.js?:1009:9)
    at Object.Index._render (webpack:///./src/routes/index.html?:49:120)
    at Object.Layout._render (webpack:///./src/routes/_layout.html?:45:276)
    at Object.Layout.render (webpack:///./src/routes/_layout.html?:23:20)
    at Promise.all.catch.then.preloaded (webpack:///./__sapper__/server.js?:2193:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by RobBrazier** [comment]
Really sorry for the delay :disappointed:. Support has been added for svelte 3 now in `2.0.1`. I haven't tested with sapper yet (so won't close this card yet), but will try this evening. In the meantime, are you able to give it a go (if you are still interested)

**Comment by RobBrazier** [comment]
Closing as I have tested this with sapper now - all working

**Comment by adamkiss** [comment]
@RobBrazier Could you tell me /add to readme _how_ did you solve it with Sapper? I'm calling the Icon like this:

```
	import Icon from 'svelte-awesome'
	import {faBadge} from '@fortawesome/pro-duotone-svg-icons'
```

and then using like this:

```
	<Icon data={faBadge} scale=2 />
```

and while the icon loads from client side (navigation and/or rehydratation), initial HTML has the 500 error text instead of icon and dev server/build serving returns `500` upon HTML loading.

Thank you.
