### ISSUE TITLE
Export `svelte` from package.json

### ISSUE THREAD

**Issue by antony** [RobBrazier/svelte-awesome#244]
Hi,

Thanks for creating this - I'm very glad to have found it!

I've noticed that you aren't exposing a `svelte` property from `package.json` which would allow me to use this in my own project (links to uncompiled root component file).

Would you be able to expose this property please?

Thanks!

**Comment by RobBrazier** [comment]
Sorry for the delay. thanks for raising this - I haven't been keeping up with svelte news recently, but I'm glad there is finally support for the "svelte" key in package.json! I'll get this done :smile:

**Comment by RobBrazier** [comment]
sorry - I accidentally closed this by referencing it in the commit message. reopening for now

**Comment by RobBrazier** [comment]
As this has been merged and pushed into a release, I'm closing this issue. Please feel free to comment or re-open or create a new issue if it's not working as expected!

**Comment by antony** [comment]
Awesome! Thanks!
