### ISSUE TITLE
Path.html - TypeError: Cannot read property 'setAttribute' of undefined

### ISSUE THREAD

**Issue by btakita** [RobBrazier/svelte-awesome#277]
It looks like `onupdate` in `Path.html` can be called before the html is rendered, making `refs.path` undefined.

Having a guard against an undefined `refs.path` should fix the issue.

**Comment by RobBrazier** [comment]
sorry about the delay in getting around to this, I added the guard around Polygon.html and Svg.html as well, just to be safe
