### ISSUE TITLE
Does  not work with Svelte 3

### ISSUE THREAD

**Issue by bigjoevtrj** [RobBrazier/svelte-awesome#430]
ref should be replaced with bind:this

**Comment by stychu** [comment]
[!] (svelte plugin) ParseError: The ref directive is no longer supported — use bind:this={icon} instead

**Comment by RobBrazier** [comment]
I haven't had a chance to work on this for a while... it seems svelte has changed quite a bit since I looked last. I'm going to have to read through the docs again. I'll try and get this fixed ASAP

**Comment by DerekJR321** [comment]
Is this project dead? :(

**Comment by LaughingBubba** [comment]
starting to look like it

**Comment by RobBrazier** [comment]
sorry for the delay, plethora of CI issues and life getting in the way. 2.0.0 published now with svelte 3 compatibility
