### ISSUE TITLE
New version on NPM

### ISSUE THREAD

**Issue by bcharbonnier** [RobBrazier/svelte-awesome#484]
Hello,

I can see that PR for svelte 3 compatibility has been merged into master back in May, which is 👍, nonetheless, could we think about having a/this new version published on NPM ?

Thanks for the work!

**Comment by RobBrazier** [comment]
Sorry - yeah, I've been having problems with my CI. I'll try and get this published ASAP (hopefully today)

**Comment by RobBrazier** [comment]
published now. Unfortunately I don't have any running projects at the moment using this, other than the inbuilt example project. can you try 2.0.0?

https://robbrazier.github.io/svelte-awesome/

**Comment by bcharbonnier** [comment]
Just tried `2.0.1`
Works like a charm 👍 as expected

Thank you very much!
