### ISSUE TITLE
display inline 

### ISSUE THREAD

**Issue by weepy** [RobBrazier/svelte-awesome#488]
how is it possible to display inline ?

**Comment by RobBrazier** [comment]
You should just be able to do
```
<Icon name={name} style="display:inline"></Icon>
```
If you need to explicitly define the display style.
It should already be inline by default though (after playing with my example page).

**Comment by weepy** [comment]
it seems to be "inline-block" for me ? 

I tried adding the style - but I don't think it's passed down ?

**Comment by RobBrazier** [comment]
must have broken that when upgrading to svelte 3 :(
It's now fixed/added in v2.2.0
