### ISSUE TITLE
How to use icon that doesn't come with this repo?

### ISSUE THREAD

**Issue by oren** [RobBrazier/svelte-awesome#528]
I found Icon that I want to use but it's not part of this repository. How do I add it to my svelte/sapper app? https://fontawesome.com/icons/utensils?style=solid

**Comment by RobBrazier** [comment]
Have a look at the README, you can import the icon from `@fortawesome/free-solid-svg-icons` and pass it into data as with the normal icons

**Comment by oren** [comment]
Thanks!
