### ISSUE TITLE
CSS font-size does not work for sapper app icons. 

### ISSUE THREAD

**Issue by wenwuwu** [RobBrazier/svelte-awesome#576]
Hello, 

I am building an app using Sapper and Font-awesome Icon Pro, and of course svelte-awesome. 
I encountered a problem that setting font-size on Icons does not work (after I migrated my code from svelte to sapper)

![企业微信截图_6f3656d5-61ca-4e03-ad09-638107da9419](https://user-images.githubusercontent.com/15991545/76390121-c4c2a400-63a7-11ea-99cd-1ced997b1c27.png)

It might be a problem with Font-awesome icons. I checked @fort-awesome source code in Node_modules folder, and there is no source code but only compiled code ( not sure if there is the cause )

**Comment by wenwuwu** [comment]
Here is part of my component's source code ( Style code was not rendered correctly so I removed it ) : 

`<script>
    import { createEventDispatcher } from 'svelte';
    import Icon from 'svelte-awesome/components/Icon.svelte';
    import { faTimesCircle } from '@fortawesome/pro-solid-svg-icons';

    export let hideIconClear = false;
    export let editing = false;

    const dispatch = createEventDispatcher();

    function clear () {
        sendMsg('clear', true);
    }
    function sendMsg (type, value) {
        let obj = {};
        obj[type] = value;

		dispatch('message', obj);
	}
</script>

<div class="text-box-wrap" class:editing>
    <div class="left">
        <slot />
    </div> 
    <div class="menu-wrap" class:hideIconClear on:click={clear}>
        <div class="bg"></div>
        <div class="clear">
            <Icon data={faTimesCircle} />
        </div> 
    </div> 
</div> 
`

**Comment by RobBrazier** [comment]
Can I confirm, did it work in svelte but just not sapper, or did you start using svelte-awesome after you migrated over?

**Comment by wenwuwu** [comment]
> Can I confirm, did it work in svelte but just not sapper, or did you start using svelte-awesome after you migrated over?

I just tried to use svelte-awesome in my svelte app (Before I was using fontawesome-svelte), it has  the same problem: font-size does not work. This happens both in svelte and sapper.

**Comment by RobBrazier** [comment]
Okay thanks. It could be because it's a SVG that is being rendered, not actually a font, but I'll investigate if there is something that can be done to make it work better inline

**Comment by wenwuwu** [comment]
Thanks a lot. Actually setting width and height on svg element directly still works. But I would like to keep it consistent between svelte and sapper, and keep on using font-size when using fontawesome icons (and for my old projects) . It will help a lot if font-size works as usually. thanks again for investigation.

**Comment by benmccann** [comment]
Sapper's basically EOL at this point. I'd recommend using SvelteKit. It works for me on the latest SvelteKit now. I don't have to do the Sapper workaround either and can just do `import Icon from 'svelte-awesome';`

**Comment by RobBrazier** [comment]
provisionally closing as sapper is deprecated now over sveltekit

**Comment by Raynard87645** [comment]
You can add a root style  and import into main icon div by add style attribute to div
:root {
  --color: #000;
}
.main {
color: var(--color);
}
<div class="main" style="--color: red">
<MdNotificationsActive />
</div>
