### ISSUE TITLE
How to use it exactly

### ISSUE THREAD

**Issue by PlkMarudny** [RobBrazier/svelte-awesome#610]
I am getting 

```
ReferenceError: freeSolidSvgIcons is not defined
```
on the basic example. You rollup.config.js does not contain any 'externa' nor 'output' sections, what am I doing wrong?

**Comment by RobBrazier** [comment]
rollup.config.js doesn't have any outputs because svelte recommends not publishing compiled components. You import the raw component.

The build is to ensure that the component compiles and functions correctly.

Have you added `@fortawesome/free-solid-svg-icons` to your package.json?

**Comment by PlkMarudny** [comment]
Thank you, this helped indeed. Works now. But maybe would be beneficial to add this to the README.md?
