### ISSUE TITLE
Support for using  fontawesome-pro icons

### ISSUE THREAD

**Issue by marclovesjazz** [RobBrazier/svelte-awesome#672]
It would be great if there would be a simple way to use the fontawesome-pro icons.

**Comment by RobBrazier** [comment]
I've never really used fontawesome-pro (unfortunately I can't justify paying $99/year), do you mean access to the light/duotone styles like in https://fontawesome.com/icons/address-book?style=light ?

**Comment by marclovesjazz** [comment]
Hi Rob,

Yes, that’s exactly what I want to do.
Thanks in advance for having a look at it.

Best regards,
Marc

____________________________________________
Marc Van de perre

E-mail: marc.vandeperre@interface-marketing.com
Mob: +32-475-419804

**Comment by RobBrazier** [comment]
I've been chatting with the fontawesome guys and it seems like the pro icons should be compatible with this component already, you just need to import the icons in the same manner as the free icons

Feel free to re-open if you're still having issues and can you give more info as to the error if necessary - cheers
