### ISSUE TITLE
Importing Icons with Hyphens

### ISSUE THREAD

**Issue by Xevinaly** [RobBrazier/svelte-awesome#729]
I'm getting parse errors when using ES6 to import some of the icons due to the hyphens used.

I have searched for a solution to this online but found none. What is the recommended way to use the icons that export names with hyphens?

**Comment by RobBrazier** [comment]
Are you using the embedded font awesome v4 icons or font awesome v5?

For v4, all of the kebab-case icons are converted to camel-case and are exported by icons/index.js (see the README - e.g. `import {codeFork} from 'svelte-awesome/icons'`

Unless things have changed recently, font-awesome v5 also does the same thing

Could you give an example of what you're trying to do?

**Comment by Xevinaly** [comment]
I was trying to import angle-down from the icons folder using:
`import { angle-down } from 'svelte-awesome/icons';`
which causes a syntax error. Using camelCase as recommended it says that the specified export can't be found.

The workaround I ended up using was:
`import * as angledown from 'svelte-awesome/icons/angle-down.js';`
followed by
`<Icon data={angledown.default} />`

**Comment by RobBrazier** [comment]
I just tested this locally to sanity check, generally you can't use hyphens in JS variables
**angleDown** is exported by svelte-awesome/icons/index.js

you need to do
```
import { angleDown } from 'svelte-awesome/icons';
```
and that should work fine

Which version of svelte-awesome are you using?

**Comment by Xevinaly** [comment]
Hey Rob, I opened a new project to see if I could recreate the issue, and I could not. I must have had some other problem, which I mistakenly interpreted as a problem with Svelte Awesome.
Thank you so much for your help, and sorry for giving you a scare.

**Comment by RobBrazier** [comment]
@Xevinaly ah awesome, no worries - glad you got it sorted in the end :)
