### ISSUE TITLE
not working in sveltekit

### ISSUE THREAD

**Issue by eikaramba** [RobBrazier/svelte-awesome#736]
getting error in sveltekit (also tried sapper approach from readme)

```
export { default as glass } from './glass';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (node:internal/modules/cjs/loader:1024:16)
```

**Comment by BrettBurbidge** [comment]
Same issue as @eikaramba

**Comment by benmccann** [comment]
It works for me on the latest SvelteKit now. I don't have to do the Sapper workaround either and can just do `import Icon from 'svelte-awesome';`

**Comment by eikaramba** [comment]
i can confirm, svelte kit next 77 did not work, with SvelteKit v1.0.0-next.85 it works. perfect!

**Comment by wallw-bits** [comment]
I'm getting this on SvelteKit v1.0.0-next.162 when running `dev` and the following when running `build`:

```
...
> Using @sveltejs/adapter-node
> Directory import '<project>/node_modules/svelte-awesome/icons' is not supported resolving ES modules imported from <project>/packages/app/.svelte-kit/output/server/app.js
Did you mean to import svelte-awesome/icons/index.js?
```

Would this be fixed by adding explicit exports a la [the fix in this PR to rxjs](https://github.com/ReactiveX/rxjs/pull/6192/files)?

**Comment by benmccann** [comment]
`@fortawesome/free-solid-svg-icons` works because it's an npm package: https://npmjs.com/package/@fortawesome/free-solid-svg-icons

`svelte-awesome/icons` doesn't work because it's a directory within an npm package. Adding `exports` to `package.json` like you mentioned sounds like a good solution to this

**Comment by RobBrazier** [comment]
for anyone who still has the issue, can you try the latest version - this has the exports now and is built with svelte-kit package, so has typescript definitions too
