### ISSUE TITLE
"Problems" in vscode

### ISSUE THREAD

**Issue by olivierchatry** [RobBrazier/svelte-awesome#774]
Hello !

First thanks for this library, it's great.

Got a bit of an issue while using vscode. It seems like everytime we use the Icon components, two new "problem" appears in the "problems" tabs of VSCode:

1. 
```
Element does not support attributes because type definitions are missing for this Svelte Component or element cannot be used as such.

Underlying error:
JSX element class does not support attributes because it does not have a '$$prop_def' property.
```

2. 
```
Type definitions are missing for this Svelte Component. It needs a class definition with at least the property '$$prop_def' which should contain a map of input property definitions.
Example:
  class ComponentName { $$prop_def: { propertyName: string; } }
If you are using Svelte 3.31+, use SvelteComponentTyped:
  import type { SvelteComponentTyped } from "svelte";
  class ComponentName extends SvelteComponentTyped<{propertyName: string;}> {}

Underlying error:
'Icon' cannot be used as a JSX component.
  Its instance type 'Icon' is not a valid JSX element.
```

**Comment by RobBrazier** [comment]
I suspect this might be because Svelte components aren't intended to be JSX compatible https://github.com/sveltejs/svelte/issues/2509

What extension is flagging these problems?

**Comment by olivierchatry** [comment]
I'm using this set of extensions: 

https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode

I think I have read somewhere that the svelte language server actually convert to TSX:

https://github.com/sveltejs/language-tools which use this : https://github.com/sveltejs/language-tools/tree/master/packages/svelte2tsx

So that might be the issue ?

**Comment by dummdidumm** [comment]
Are you using the component in a project with TypeScript (`lang="ts"` on your Svelte component script tags)? The error roughly means that type definitions are missing (although I'm wondering why you get that error message, and not `Could not find a declaration file for module 'svelte-awesome'` which I get).
So in order to fix this, type definitions ( `d.ts` files) need to be added.

**Comment by olivierchatry** [comment]
Nope we are using plain old JavaScript. Not to sure why I get this error.

**Comment by RobBrazier** [comment]
could you try with 2.4.0? I've integrated the svelte-kit additional parts, which hopefully should satisfy the plugin

**Comment by olivierchatry** [comment]
of course !

**Comment by olivierchatry** [comment]
yup, seems to work now ! Thanks alot !

the only small issue it tells me is about scale not being a string when I
do that :

<Icon data={faPlus} scale={0.8} />

**Comment by RobBrazier** [comment]
awesome - 2.4.1 coming shortly should fix that one too

**Comment by olivierchatry** [comment]
Great ! Thanks again.
