### ISSUE TITLE
SvelteKit Error

### ISSUE THREAD

**Issue by kane81** [RobBrazier/svelte-awesome#775]
Hi,

I tried using svelte-awesome in a SvelteKit project 
```
<script>
	import Icon from 'svelte-awesome';
	import { beer } from 'svelte-awesome/icons';
</script>

<Icon data={beer} />
```

and get the following errors

Failed to fetch dynamically imported module: http://localhost:3000/src/routes/index.svelte
TypeError: Failed to fetch dynamically imported module: http://localhost:3000/src/routes/index.svelte

Uncaught (in promise) TypeError: Failed to fetch
index.js:556 GET http://localhost:3000/node_modules/svelte-awesome/icons/buysellads.js?v=4e79ebf0 net::ERR_FAILED

I tried 

`import Icon from 'svelte-awesome/components/Icon.svelte'`

but it didnt work either....

**Comment by RobBrazier** [comment]
Can you try disabling your adblocker if you have one - chances are that's the cause for buysellads.js being blocked

When is this happening? when you run npm run dev / svelte-kit dev?

I'm seeing the same error when I run it with dev, but works absolutely fine when I do npm run build, then npm run preview - I can only assume it's something to do with the hmr.

**Comment by RobBrazier** [comment]
yep - that's the issue, adblock is blocking buysellads.js, which svelte doesn't like.
