### ISSUE TITLE
Updated default to v5 of fontawesome

### ISSUE THREAD

**Issue by gaurovsoni** [RobBrazier/svelte-awesome#776]
Since v5 have many new icons, its time now to upgrade to v5 to be used by default with svelte-awesome. This enhancement would be appreciated.

**Comment by RobBrazier** [comment]
I'm not planning on embedding (or maintaining) the v5 icons. The only reason why it was done for v4 is that there were no packages.
If you want to use v5, please use the `@fortawesome` packages as documented in the README

**Comment by AdaptingAFM** [comment]
> I'm not planning on embedding (or maintaining) the v5 icons. The only reason why it was done for v4 is that there were no packages. If you want to use v5, please use the `@fortawesome` packages in addition to this component as documented in the README

Hey! I'm using the @fortawesome packages, but as they are CommonJS modules I am thrown of an error when compiling my Kit: 

```bash
import { faEyeSlash, faBarsProgress, faMoneyCheckAlt, faDiagramProject, faChartSimple, faArrowTrendUp, faBarsStaggered, faAnglesDown } from "@fortawesome/free-solid-svg-icons";
                                                                                                                        ^^^^^^^^^^^^
SyntaxError: Named export 'faAnglesDown' not found. The requested module '@fortawesome/free-solid-svg-icons' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@fortawesome/free-solid-svg-icons';
const { faEyeSlash, faBarsProgress, faMoneyCheckAlt, faDiagramProject, faChartSimple, faArrowTrendUp, faBarsStaggered, faAnglesDown } = pkg;
```
