### ISSUE TITLE
Importing icons with "-"

### ISSUE THREAD

**Issue by lucasnad27** [RobBrazier/svelte-awesome#815]
Excuse me for being dense, as I'm sure this is on my end. Javascript isn't my first language and I'm not sure how to get around this.

If I take the examples from the docs and want to use an outlined version of an icon, this is what the syntax looks like, albeit invalid.

`import { heart-o } from 'svelte-awesome/icons';`

Linting complains and I can't get the `heart-o` to import due to the "-" in the javascript file. Any help would be much appreciated. If you have an obvious answer, I'd be happy to take that answer and create a PR to improve the docs for this use case, as using outline vs solid versions of icons is a common feature in other libraries. I doubt I'm the first to run into this. Thank you for this library!!

**Comment by RobBrazier** [comment]
I probably need to clarify this in the documentation - any icons with dashes are imported as camelCase, e.g.
`import { heartO } from 'svelte-awesome/icons';`

If you want to raise a PR to update the docs that'd be ace, I'm going to work on some more in-depth documentation as well, as it's currently a little sparse with just a few examples.

I see there is `codeFork` in the README but it's not really obvious that this is the `code-fork` icon - https://github.com/RobBrazier/svelte-awesome#usage

**Comment by lucasnad27** [comment]
Aces @RobBrazier. Appreciate the quick response. I've done my best to make it more explicit in the README, but it's tricky.

I should mention that the moment I saw your response I saw `heartO` pop up on my auto-complete when fixing my code 😳
