### ISSUE TITLE
cannot update to 2.4.3

### ISSUE THREAD

**Issue by olivierchatry** [RobBrazier/svelte-awesome#821]
Hello !
Thanks agan for the fantastic work :)
When I try to update ( or install ) 2.4.3, I get this error: 
```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name ">=3.43.1,<4.0.0": Tags may not have any characters that encodeURIComponent encodes.
```

**Comment by RobBrazier** [comment]
apologies - sorted now, 2.4.4 is releasing shortly

**Comment by olivierchatry** [comment]
No worries, thanks a lot for fixing it this fast !

**Comment by Mx-unix** [comment]
Thank you for fixing this again!
