### ISSUE TITLE
Hundreds of Network Requests When Importing One Icon

### ISSUE THREAD

**Issue by teamjordy** [RobBrazier/svelte-awesome#849]
**Observed Behavior:**

Importing the svelte-awesome package and icons (or a single icon) triggers hundreds of JS requests. In my app the total HTTP requests jumped from 52 to 839.

**Steps to reproduce:**

In `package.json` dependencies:
```
"svelte-awesome": "^2.4.6"
```

In any `.svelte` component:
```
import Icon from 'svelte-awesome';
import { times } from 'svelte-awesome/icons';
```

Observe the Network tab in dev tools and see the difference when `import { times } from 'svelte-awesome/icons';` is removed from the component.

**Expected Behavior:**
Unless I'm misunderstanding or importing this wrong, I'd expect importing one icon to make one additional request.

**Comment by RobBrazier** [comment]
please can you check with v3.0.0?
I have introduced another import option which should be less intensive
```js
import times from 'svelte-awesome/icons/times';
```

I've also added a new page with an index of all available embedded v4 icons - https://docs.robbrazier.com/svelte-awesome/icons (no search yet, but Ctrl-F is your friend)
