### ISSUE TITLE
Possible to import icons dynamically?

### ISSUE THREAD

**Issue by cascading-jox** [RobBrazier/svelte-awesome#878]
I am trying to render icons depending on strings with the icon names that I initiate the component with. Is it possible to import icons dynamically depending on a configuration set at runtime e.g. from a string? It seems like including fontawesome in a link tag doesn't render `<i>` tags in web components with their own shadow root (haven't tested without customElements: true).

**Comment by RobBrazier** [comment]
really sorry for the delay in replying - you can handle that in your application, keeping a map of string -> icon data like you're mentioning - the Icon will update when you change the data assigned to it
