### ISSUE TITLE
Invalid HTML when using multiple icons

### ISSUE THREAD

**Issue by w3rafu** [RobBrazier/svelte-awesome#896]
Hello, Rob.

After running w3 validator, I found multiple errors caused by icons path duplicating ID's.

They all render the same ID.

e.g.
`<path id="path-0" ... >`
`<path id="path-0" ... >`
`<path id="path-0" ... >`

Any workaround for this?

Thanks!

**Comment by inbetweencode** [comment]
I am actually on this issue because I think to have extra information.

The first icon on the page is normal: having a single <path>.
Subsequent SVG's have respectively 3, 5 and 6 <path>'s.
I have no explaination for this behaviour.

**Comment by josdejong** [comment]
These id's are generated here:

https://github.com/RobBrazier/svelte-awesome/blob/effeff0a5f99ff5467b311ba8ea8943493356e28/src/lib/components/Icon.svelte#L5-L8

Which creates a `Path` component with (mostly) `id="path-0"`

https://github.com/RobBrazier/svelte-awesome/blob/effeff0a5f99ff5467b311ba8ea8943493356e28/src/lib/components/svg/Path.svelte#L1

I guess the solution would be to remove the `id` attribute from paths (they can never be unique this way when you use the same icon twice).

**Comment by josdejong** [comment]
I created a PR with a possible fix: #930
