### ISSUE TITLE
[Suggestion] Improved `externalLink` icon

### ISSUE THREAD

**Issue by squidee100** [RobBrazier/svelte-awesome#897]
Is it possible to use a better, more uniform svg for the external link icon? Something like this...
```
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"
    aria-hidden="true" class="w-5 h-5">
    <path stroke-linecap="round" stroke-linejoin="round" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"></path>
</svg>
```
<img src="https://user-images.githubusercontent.com/29834597/181877937-ae588e79-988a-4527-8dc4-d9604bfbd655.svg" width="100" height="100" />

If so, could I open a PR for this?

**Comment by RobBrazier** [comment]
Unfortunately this library is intended to wrap fontawesome (not my icons) so not looking to change their icons really.

The library does support custom icons, but admittedly the documentation is pretty awful currently, you can see an example in https://github.com/RobBrazier/svelte-awesome/blob/master/src/routes/index.svelte#L113

Fair warning I am planning on changing this format at some point, but will be on a breaking version change and I'll try to document the migration.
