### ISSUE TITLE
doesn't work with webpack when using named imports

### ISSUE THREAD

**Issue by woss** [RobBrazier/svelte-awesome#940]
the type is set to `module`, which means that the imports must be valid ESM, end with the `.js` which the `icons/index.js` does not have, and this breaks imports in webpack. 

Here is the screenshot of the portion of the errors
![image](https://user-images.githubusercontent.com/80440/208167970-431a35b5-f1e3-4b39-9ef9-553e8786817c.png)

**Comment by RobBrazier** [comment]
Please can you provide a snippet of the code you're using?

Can you try using https://docs.robbrazier.com/svelte-awesome/icons instead of importing from index.js and see if that works better?

**Comment by woss** [comment]
yes, that worked, i just tried then i saw your message.

Thing is that the valid ESM requires the `.js`, you can read about it here https://nodejs.org/api/esm.html#import-specifiers
